# -*- coding: utf-8 -*-
"""Task 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chDEe9_QDzucLuZ9Eqj2N1exKuFis5go
"""



import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
file_path_population = "API_SP.POP.TOTL_DS2_en_csv_v2_76253.csv"
df_population = pd.read_csv(file_path_population, skiprows=4)  # Skipping initial metadata rows

# Select the year for visualization
year = "2023"

# Filter and sort data for better visualization
df_population_filtered = df_population[["Country Name", year]].dropna()
df_population_filtered = df_population_filtered.sort_values(by=year, ascending=False).head(20)  # Top 20 countries

# Plot bar chart
plt.figure(figsize=(12, 6))
plt.barh(df_population_filtered["Country Name"], df_population_filtered[year], color='skyblue')
plt.xlabel("Population")
plt.ylabel("Country")
plt.title(f"Top 20 Most Populous Countries in {year}")
plt.gca().invert_yaxis()  # Invert y-axis for better readability
plt.show()